image: { repository: ghcr.io/runatlantis/atlantis, tag: "v0.30.0" }
orgAllowlist: github.com/prabhat-roy/CivicLink
github:
  user: civiclink-bot
  token: { secretName: atlantis-github, secretKey: token }
  webhookSecret: { secretName: atlantis-github, secretKey: webhook-secret }
serverConfig:
  repos:
    - id: github.com/prabhat-roy/CivicLink
      apply_requirements: [approved, mergeable]
      allowed_overrides: [workflow]
      allow_custom_workflows: true
      pre_workflow_hooks:
        - { run: "infracost breakdown --path=." }
        - { run: "checkov -d ." }
ingress:
  enabled: true
  host: atlantis.civiclink.internal
