apiVersion: v1
kind: Service
metadata:
  name: emergency-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: emergency-service, civiclink.io/domain: public-safety }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50201, targetPort: 50201 }]
  selector: { app.kubernetes.io/name: emergency-service }