apiVersion: v1
kind: Service
metadata:
  name: mfa-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: mfa-service, civiclink.io/domain: identity-access }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50023, targetPort: 50023 }]
  selector: { app.kubernetes.io/name: mfa-service }