apiVersion: v1
kind: Service
metadata:
  name: traffic-violation
  namespace: civiclink
  labels: { app.kubernetes.io/name: traffic-violation, civiclink.io/domain: public-safety }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50202, targetPort: 50202 }]
  selector: { app.kubernetes.io/name: traffic-violation }