# GCP overlay for case-management.
cloud:
  provider: gcp
  storageClass: pd-balanced
  ingressClass: gce

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: civiclink-case-management@{{ .Values.gcp.project }}.iam.gserviceaccount.com

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

# Pulled by GCP Secret Manager CSI driver
envFrom:
  - secretRef:
      name: case-management-gcp-secrets