apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-exchange-gateway.fullname" . }}
  labels: {{- include "data-exchange-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "data-exchange-gateway.selectorLabels" . | nindent 4 }}