apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: civiclink
  namespace: argocd
spec:
  description: CivicLink platform applications
  sourceRepos:
    - https://github.com/prabhat-roy/CivicLink.git
  destinations:
    - { namespace: civiclink, server: https://kubernetes.default.svc }
    - { namespace: civiclink-*, server: https://kubernetes.default.svc }
  clusterResourceWhitelist:
    - { group: '*', kind: '*' }
  namespaceResourceWhitelist:
    - { group: '*', kind: '*' }