# AWS overlay for e-receipt-service.
cloud:
  provider: aws
  storageClass: gp3
  ingressClass: alb

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/civiclink-e-receipt-service

podAnnotations:
  iam.amazonaws.com/role: civiclink-e-receipt-service

# Pulled by AWS Secrets Manager CSI driver
envFrom:
  - secretRef:
      name: e-receipt-service-aws-secrets