apiVersion: v1
kind: Service
metadata:
  name: biometric-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: biometric-service, civiclink.io/domain: citizen-identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50042, targetPort: 50042 }]
  selector: { app.kubernetes.io/name: biometric-service }