spark.jars.packages=io.openlineage:openlineage-spark_2.12:1.21.0
spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.transport.type=http
spark.openlineage.transport.url=http://marquez.observability:5000
spark.openlineage.namespace=civiclink-spark
