# Azure overlay for access-log-service.
cloud:
  provider: azure
  storageClass: managed-csi
  ingressClass: azure-application-gateway

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.clientId }}"

podLabels:
  azure.workload.identity/use: "true"

# Pulled by Azure Key Vault CSI driver
envFrom:
  - secretRef:
      name: access-log-service-azure-secrets