apiVersion: v1
kind: Service
metadata:
  name: certificate-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: certificate-service, civiclink.io/domain: education }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50183, targetPort: 50183 }]
  selector: { app.kubernetes.io/name: certificate-service }