apiVersion: v1
kind: Service
metadata:
  name: citizen-sso
  namespace: civiclink
  labels: { app.kubernetes.io/name: citizen-sso, civiclink.io/domain: identity-access }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50022, targetPort: 50022 }]
  selector: { app.kubernetes.io/name: citizen-sso }