apiVersion: v1
kind: Service
metadata:
  name: national-id-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: national-id-service, civiclink.io/domain: citizen-identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50040, targetPort: 50040 }]
  selector: { app.kubernetes.io/name: national-id-service }