apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-change-service
  namespace: civiclink
  labels:
    app.kubernetes.io/name: name-change-service
    app.kubernetes.io/part-of: civiclink
    civiclink.io/domain: civil-registration
spec:
  replicas: 2
  selector: { matchLabels: { app.kubernetes.io/name: name-change-service } }
  template:
    metadata:
      labels: { app.kubernetes.io/name: name-change-service, civiclink.io/domain: civil-registration }
    spec:
      serviceAccountName: name-change-service
      securityContext: { runAsNonRoot: true, runAsUser: 1000, fsGroup: 1000 }
      containers:
        - name: name-change-service
          image: harbor.civiclink.internal/civiclink/name-change-service:latest
          ports: [{ containerPort: 50063, name: http }]
          envFrom: [{ configMapRef: { name: name-change-service } }]
          livenessProbe:  { httpGet: { path: /healthz, port: 50063 }, initialDelaySeconds: 15 }
          readinessProbe: { httpGet: { path: /healthz, port: 50063 }, initialDelaySeconds: 5 }
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits:   { cpu: 1000m, memory: 512Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }