apiVersion: v1
kind: Service
metadata:
  name: name-change-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: name-change-service, civiclink.io/domain: civil-registration }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50063, targetPort: 50063 }]
  selector: { app.kubernetes.io/name: name-change-service }