apiVersion: v1
kind: Service
metadata:
  name: e-receipt-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: e-receipt-service, civiclink.io/domain: payments-finance }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50243, targetPort: 50243 }]
  selector: { app.kubernetes.io/name: e-receipt-service }