apiVersion: v1
kind: ConfigMap
metadata:
  name: treasury-service
  namespace: civiclink
  labels: { app.kubernetes.io/name: treasury-service, civiclink.io/domain: payments-finance }
data:
  LOG_LEVEL: info
  PORT: "50241"